server:
  port: 8080

spring:
  application:
    name: student-management-system
  main:
    allow-circular-references: true
  
  datasource:
    url: jdbc:h2:mem:student_management
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# 自定義配置
app:
  upload:
    path: ./uploads/
  qr:
    path: ./qr-codes/
  security:
    jwt:
      secret: studentManagementSystemSecretKey2024
      expiration: 86400000 # 24小時

# 日誌配置
logging:
  level:
    com.student: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 